spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ECommCRUD
  datasource:
    url: jdbc:h2:file:C:\temp\ecom
    username: sa
    password: pra
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
     console:
       enabled: true